#!/bin/sh

N=5 # number of times a test is repeated (to get an average)

# TIP: You can edit the list of input sizes below
for size in 10000 20000 40000 80000 160000 320000 500000
do
	# TIP: You can edit the list of input types below
	#      For example, you could remove 'random' if you don't want to
	#      time with random input
	for order in random sorted reversed
	do
		echo === Testing for $order input, size $size ===
		for i in $(seq $N)
		do
			case $order in
				random)   flag="R" ;;
				sorted)   flag="A" ;;
				reversed) flag="D" ;;
			esac
			{ ./gen $size $flag | mydata > /usr/bin/time -f "%U" ./sortA > /dev/null ; }
			#                          TIP: replace this ^ with ./sortA or ./sortB./
		done
		echo ""
	done
done

